namespace Bizer.AspNetCore.Components;

internal enum IconName
{
    Activity,
    Airplane,
    [CssClass("airplane-fill")] AirplaneFill,
    [CssClass("airplane-engines")]AirplaneEngines,
    [CssClass("airplane-engines-fill")] AirplaneEnginesFill,
    Alarm,
    [CssClass("alarm-fill")]AlarmFill,
    [CssClass("align-bottom")]AlignBottom,
    [CssClass("align-center")] AlignCenter,
    [CssClass("align-end")] AlignEnd,
    [CssClass("align-middle")] AlignMiddle,
    [CssClass("align-start")] AlignStart,
    [CssClass("align-top")] AlignTop,
    Alipay,
    Amd,
    Alt,
    Android,
    Android2,
    App,
    [CssClass("app-indicator")]AppIndicator,
    Apple,
    Archive,
    [CssClass("archive-fill")]ArchiveFill,
    [CssClass("arrow-90deg-down")]Arrow90DegDown,
    [CssClass("arrow-90deg-left")] Arrow90DegLeft,
    [CssClass("arrow-90deg-right")] Arrow90DegRight,
    [CssClass("arrow-90deg-up")] Arrow90DegUp,
    [CssClass("arrow-bar-down")]ArrowBarDown,
    [CssClass("arrow-bar-left")] ArrowBarLeft,
    [CssClass("arrow-bar-right")] ArrowBarRight,
    [CssClass("arrow-bar-up")] ArrowBarUp,
    [CssClass("arrow-clockwise")]ArrowClockwise,
    [CssClass("arrow-counterclockwise")] ArrowCounterClockwise,
    [CssClass("arrow-down")]ArrowDown,
    [CssClass("arrow-down-circle")]ArrowDownCircle,
    [CssClass("arrow-down-circle-fill")] ArrowDownCircleFill,
    [CssClass("arrow-down-square")] ArrowDownSquare,
    [CssClass("arrow-down-square-fill")] ArrowDownSquareFill,
    At,
    [CssClass("bar-chart")]BarChart,
    [CssClass("bar-chart-fill")] BarChartFill,
    [CssClass("bar-chart-line")] BarChartLine,
    [CssClass("bar-chart-line-fill")] BarChartLineFill,
    [CssClass("bar-chart-steps")] BarChartSteps,
    Bell,
    [CssClass("bell-fill")]BellFill,
    [CssClass("bell-slash")]BellSlash,
    [CssClass("bell-slash-fill")] BellSlashFill,
    [CssClass("box-arrow-in-down")]BoxArrowInDown,
    [CssClass("box-arrow-in-left")] BoxArrowInLeft,
    [CssClass("box-arrow-in-right")] BoxArrowInRight,
    [CssClass("box-arrow-in-up")] BoxArrowInUp,
    [CssClass("box-arrow-down")]BoxArrowDown,
    [CssClass("box-arrow-up")] BoxArrowUp,
    [CssClass("box-arrow-right")] BoxArrowRight,
    [CssClass("box-arrow-left")] BoxArrowLeft,
    Calendar,
    [CssClass("calendar-check")]CalendarCheck,
    [CssClass("calendar-check-fill")] CalendarCheckFill,
    [CssClass("calendar-date")]CalendarDate,
    [CssClass("calendar-date-fill")] CalendarDateFill,

    Calendar2,
    [CssClass("calendar2-check")] Calendar2Check,
    [CssClass("calendar2-check-fill")] Calendar2CheckFill,
    [CssClass("calendar2-date")] Calendar2Date,
    [CssClass("calendar2-date-fill")] Calendar2DateFill,
    Calendar3,
    [CssClass("calendar3-check")] Calendar3Check,
    [CssClass("calendar3-check-fill")] Calendar3CheckFill,
    [CssClass("calendar3-date")] Calendar3Date,
    [CssClass("calendar3-date-fill")] Calendar3DateFill,

    Calendar4,
    [CssClass("calendar4-check")] Calendar4Check,
    [CssClass("calendar4-check-fill")] Calendar4CheckFill,
    [CssClass("calendar4-date")] Calendar4Date,
    [CssClass("calendar4-date-fill")] Calendar4DateFill,

    Chat,
    [CssClass("chat-fill")]ChatFill,
    [CssClass("chat-dots")]ChatDots,
    [CssClass("chat-dots-fill")] ChatDotsFill,

    [CssClass("chat-left")]ChatLeft,
    [CssClass("chat-left-fill")] ChatLeftFill,
    [CssClass("chat-left-dots")] ChatLeftDots,
    [CssClass("chat-left-dots-fill")] ChatLeftDotsFill,
    [CssClass("chat-right")] ChatRight,
    [CssClass("chat-right-fill")] ChatRightFill,
    [CssClass("chat-right-dots")] ChatRightDots,
    [CssClass("chat-right-dots-fill")] ChatRightDotsFill,
    Check,
    [CssClass("check-all")]CheckAll,
    [CssClass("check-circle")]CheckCircle,
    [CssClass("check-circle-fill")]CheckCircleFill,
    [CssClass("check-square")]CheckSquare,
    [CssClass("check-square-fill")]CheckSquareFill,
    Envelope,
    [CssClass("envelope-open")]EnvelopeOpen,
    [CssClass("envelope-open-fill")] EnvelopeOpenFill,

    Exclamation,
    [CssClass("exclamation-lg")]ExclamationLarge,
    [CssClass("exclamation-circle")]ExclamtionCircle,
    [CssClass("exclamation-circle-fill")] ExclamtionCircleFill,
    [CssClass("exclamation-diamond")] ExclamtionDiamond,
    [CssClass("exclamation-diamond-fill")] ExclamtionDiamondFill,
    [CssClass("exclamation-square")] ExclamtionSquare,
    [CssClass("exclamation-square-fill")] ExclamtionSquareFill,
    [CssClass("exclamation-triangle")] ExclamtionTriangle,
    [CssClass("exclamation-triangle-fill")] ExclamtionTriangleFill,
    Funnel,
    [CssClass("funnel-fill")]FunnelFill,
    Gear,
    [CssClass("gear-fill")]GearFill,
    Info,
    [CssClass("info-circle")]InfoCircle,
    [CssClass("info-circle-fill")] InfoCircleFill,
    [CssClass("info-square")] InfoSquare,
    [CssClass("info-square-fill")] InfoSquareFill,
    List,
    [CssClass("list-check")] ListCheck,
    [CssClass("list-task")]ListTask,
    [CssClass("list-ol")] ListOl,
    [CssClass("list-ul")]ListUl,
    Lock,
    [CssClass("lock-fill")]LockFill,
    Pencil,
    [CssClass("pencile-fill")]PencilFill,
    [CssClass("pencil-square")]PencilSquare,
    [CssClass("person-circle")]PersonCircle,
    Person,
    [CssClass("person-add")]PersonAdd,
    [CssClass("persons-gear")] PersonGear,
    [CssClass("persons-square")] PersonSquare,
    [CssClass("persons-plus")] PersonPlus,
    [CssClass("persons-plus-fill")] PersonPlusFill,
    Plus,
    [CssClass("plus-circle")]PlusCircle,
    [CssClass("plus-circle-fill")]PlusCircleFill,
    [CssClass("plus-square")] PlusSqaure,
    [CssClass("plus-square-fill")] PlusSquareFill,
    Search,
    Share,
    [CssClass("share-fill")]ShareFill,
    Send,
    [CssClass("send-fill")]SendFill,
    Star,
    Stars,
    [CssClass("star-fill")]StarFill,
    [CssClass("star-half")]StarHalf,

    Tag,
    [CssClass("tag-fill")]TagFill,
    Tags,
    [CssClass("tags-fill")]TagsFill,
    X,
    [CssClass("x-circle")]XCircle,
    [CssClass("x-circle-fill")] XCircleFill,
    [CssClass("x-square")] XSquare,
    [CssClass("x-square-fill")] XSquareFill,
    [CssClass("zoom-in")]ZoomIn,
    [CssClass("zoom-out")]ZoomOut
}
